---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-slave
  name: redis-slave
  namespace: kube-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-slave
  template:
    metadata:
      labels:
        app: redis-slave
    spec:
      containers:
        - args:
            - bash
            - -c
            - redis-server --slaveof $REDIS_MASTER_HOST 6379
          env:
            - name: REDIS_MASTER_HOST
              valueFrom:
                configMapKeyRef:
                  key: REDIS_MASTER_HOST
                  name: env-config
          image: redis
          name: redis-slave
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
