---
kind: Service
apiVersion:  v1
metadata:
  name: es
  namespace: kube-logging
  labels:
    app: es
spec:
  selector:
    app: es
  clusterIP: None
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node