---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  namespace: kube-logging
  labels:
    app: redis-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-master
  template:
    metadata:
      labels:
        app: redis-master
    spec:
      containers:
        - image: redis
          name: redis-master
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
